# @package _global_

# Main configuration file that imports all sub-configurations
defaults:
  - model: roberta_lora
  - data: mrpc
  - training: lora_training
  - _self_

# Output directory (uses interpolation for dynamic naming)
output_dir: "./outputs/${model.name}_${data.name}_${now:%Y-%m-%d_%H-%M-%S}"

# Debugging flag
debug: false

# Random seed for reproducibility
seed: 42

# Hydra-specific configuration
hydra:
  job:
    chdir: true  # Change working directory to output directory
  run:
    dir: ${output_dir}/hydra_logs
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job_logging:
    handlers:
      file:
        filename: ${hydra.run.dir}/hydra.log