# Main configuration file
defaults:
  - model: roberta_lora
  - data: mrpc
  - training: lora_training
  - _self_

# Create a simpler experiment name
experiment_name: "roberta-lora-mrpc"

# Base directory for all outputs (models, logs, etc.)
base_dir: "./outputs"

# Actual output directory for model checkpoints and results
output_dir: "${base_dir}/${experiment_name}"

# Debugging flag
debug: false

# Random seed for reproducibility
seed: 42

# Hydra-specific configuration
hydra:
  # Change Hydra's own output directory to avoid path conflicts
  run:
    # Place Hydra logs in a separate directory to avoid path conflicts
    dir: "${base_dir}/hydra_logs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}"

  # For multi-run experiments (parameter sweeps)
  sweep:
    dir: "${base_dir}/multirun/${now:%Y-%m-%d}"
    subdir: ${hydra.job.num}

  # Don't change working directory to avoid path confusion
  job:
    chdir: false